version: '3.8'

services:
  dev-nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - dev-backend
      # - dev-frontend
    networks:
      - app-network
  # dev-frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   networks:
  #     - app-network
  #   ports:
  #     - "3001:3001"
  dev-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/code
    networks:
      - app-network
    
    depends_on:
      - dev-postgres
    ports:
      - "8001:8001"
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8001 
  dev-postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres

volumes:
  postgres_data:


networks:
  app-network:
    external: true