"""Init5

Revision ID: 5b7af525cc48
Revises: cd809570de4b
Create Date: 2025-07-11 21:30:44.113665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7af525cc48'
down_revision: Union[str, None] = 'cd809570de4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_book_platform', 'book_prices', ['book_id', 'platform'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_book_platform', 'book_prices', type_='unique')
    # ### end Alembic commands ###
