"""add is_anonymous to reviews and review_comments

Revision ID: 7ecb450a7425
Revises: 5fdbfb0b5fda
Create Date: 2025-07-08 20:29:33.907913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ecb450a7425'
down_revision: Union[str, None] = '5fdbfb0b5fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_comments', sa.Column('is_anonymous', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('is_anonymous', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'is_anonymous')
    op.drop_column('review_comments', 'is_anonymous')
    # ### end Alembic commands ###
